<?php

namespace ContainerBGRepez;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kdvz9V2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kdvz9V2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kdvz9V2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'inscriptionSoloRepository' => ['privates', 'App\\Repository\\InscriptionSoloRepository', 'getInscriptionSoloRepositoryService', true],
        ], [
            'inscriptionSoloRepository' => 'App\\Repository\\InscriptionSoloRepository',
        ]);
    }
}
