<?php

namespace ContainerBGRepez;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInscriptionSolo2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4MW7.KG.App\Entity\InscriptionSolo' shared service.
     *
     * @return \App\Entity\InscriptionSolo
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.4MW7.KG": it references class "App\\Entity\\InscriptionSolo" but no such service exists.');
    }
}
