<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCEGuazV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCEGuazV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCEGuazV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCEGuazV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCEGuazV\App_KernelDevDebugContainer([
    'container.build_hash' => 'CEGuazV',
    'container.build_id' => '19ff2aa8',
    'container.build_time' => 1605795095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCEGuazV');
