<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL7MQDc4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL7MQDc4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL7MQDc4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL7MQDc4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL7MQDc4\App_KernelDevDebugContainer([
    'container.build_hash' => 'L7MQDc4',
    'container.build_id' => 'd53ea83e',
    'container.build_time' => 1606123157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL7MQDc4');
