<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALTzUsk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALTzUsk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerALTzUsk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerALTzUsk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerALTzUsk\App_KernelDevDebugContainer([
    'container.build_hash' => 'ALTzUsk',
    'container.build_id' => 'a80463b9',
    'container.build_time' => 1606998408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALTzUsk');
